"""mnn.discovery.conjectures — Conjecture Generation Engine.

Engine 3: Observes mathematical structures and generates hypotheses.
Types: algebraic (commutativity, associativity), geometric (curvature),
dynamical (conserved energy), topological, PDE symmetry.
"""
from __future__ import annotations
import numpy as np
from typing import Any, Callable, Dict, List, Optional, Tuple
from dataclasses import dataclass, field
from enum import Enum
import time


class ConjectureType(Enum):
    ALGEBRAIC = "algebraic"
    GEOMETRIC = "geometric"
    DYNAMICAL = "dynamical"
    TOPOLOGICAL = "topological"
    PDE = "pde"
    SEQUENCE = "sequence"
    INVARIANCE = "invariance"
    EQUIVALENCE = "equivalence"


class ConjectureStatus(Enum):
    PROPOSED = "proposed"
    TESTING = "testing"
    SUPPORTED = "supported"
    REFUTED = "refuted"
    PROVEN = "proven"


@dataclass
class Conjecture:
    """A mathematical hypothesis generated by the discovery engine."""
    statement: str
    conjecture_type: ConjectureType
    status: ConjectureStatus = ConjectureStatus.PROPOSED
    confidence: float = 0.0
    evidence: List[Dict] = field(default_factory=list)
    counterexamples: List[Dict] = field(default_factory=list)
    source: str = ""
    timestamp: float = field(default_factory=time.time)
    metadata: Dict[str, Any] = field(default_factory=dict)

    def add_evidence(self, description: str, data: Any = None):
        self.evidence.append({"description": description, "data": data})
        self._update_confidence()

    def add_counterexample(self, description: str, data: Any = None):
        self.counterexamples.append({"description": description, "data": data})
        self.status = ConjectureStatus.REFUTED
        self.confidence = 0.0

    def _update_confidence(self):
        n_ev = len(self.evidence)
        n_cx = len(self.counterexamples)
        if n_cx > 0:
            self.confidence = 0.0
            self.status = ConjectureStatus.REFUTED
        elif n_ev >= 10:
            self.confidence = min(0.95, 0.5 + 0.05 * n_ev)
            self.status = ConjectureStatus.SUPPORTED
        elif n_ev > 0:
            self.confidence = min(0.5, 0.1 * n_ev)
            self.status = ConjectureStatus.TESTING

    def summary(self) -> str:
        return (f"[{self.status.value.upper()}] ({self.confidence:.0%}) "
                f"{self.conjecture_type.value}: {self.statement}")

    def __repr__(self):
        return self.summary()


class ConjectureGenerator:
    """Generate mathematical conjectures from observed structures.

    Examines data, operations, transformations and proposes hypotheses
    about algebraic, geometric, dynamical, and topological properties.
    """
    def __init__(self):
        self.conjectures: List[Conjecture] = []

    def analyze_operation(self, op: Callable, elements: List[Any],
                           op_name: str = "op") -> List[Conjecture]:
        """Generate algebraic conjectures about a binary operation."""
        from .patterns import SymmetryDetector
        new_conjectures = []

        # Test commutativity
        comm = SymmetryDetector.test_commutativity(op, elements)
        if comm["commutative"]:
            c = Conjecture(
                f"The operation '{op_name}' is commutative: {op_name}(a,b) = {op_name}(b,a)",
                ConjectureType.ALGEBRAIC, source="commutativity_test",
            )
            c.add_evidence(f"Tested {comm['tested']} pairs, violation rate: {comm['violation_rate']:.6f}")
            new_conjectures.append(c)

        # Test associativity
        assoc = SymmetryDetector.test_associativity(op, elements)
        if assoc["associative"]:
            c = Conjecture(
                f"The operation '{op_name}' is associative: {op_name}({op_name}(a,b),c) = {op_name}(a,{op_name}(b,c))",
                ConjectureType.ALGEBRAIC, source="associativity_test",
            )
            c.add_evidence(f"Tested {assoc['tested']} triples, violation rate: {assoc['violation_rate']:.6f}")
            new_conjectures.append(c)

        # Test identity element
        for e in elements[:min(len(elements), 10)]:
            is_identity = True
            for a in elements[:min(len(elements), 20)]:
                try:
                    if isinstance(op(e, a), np.ndarray):
                        if not np.allclose(op(e, a), a, atol=1e-8) or not np.allclose(op(a, e), a, atol=1e-8):
                            is_identity = False
                            break
                    else:
                        if abs(op(e, a) - a) > 1e-8 or abs(op(a, e) - a) > 1e-8:
                            is_identity = False
                            break
                except Exception:
                    is_identity = False
                    break
            if is_identity:
                c = Conjecture(
                    f"The element {e} is an identity for '{op_name}'",
                    ConjectureType.ALGEBRAIC, source="identity_search",
                )
                c.add_evidence(f"Verified against {min(len(elements), 20)} elements")
                new_conjectures.append(c)
                break

        self.conjectures.extend(new_conjectures)
        return new_conjectures

    def analyze_sequence(self, seq: List[float], name: str = "a") -> List[Conjecture]:
        """Generate conjectures about a numerical sequence."""
        from .patterns import SequenceAnalyzer
        info = SequenceAnalyzer.analyze(seq)
        new_conjectures = []

        if info["pattern"] != "unknown":
            formula = info.get("formula", info["pattern"])
            c = Conjecture(
                f"Sequence '{name}' follows pattern: {formula}",
                ConjectureType.SEQUENCE, source="sequence_analysis",
            )
            c.add_evidence(f"Pattern: {info['pattern']}, matched {len(seq)} terms")
            c.confidence = 0.8 if len(seq) >= 5 else 0.5
            c.status = ConjectureStatus.SUPPORTED
            new_conjectures.append(c)

        self.conjectures.extend(new_conjectures)
        return new_conjectures

    def analyze_function_symmetry(self, f: Callable, dim: int,
                                    name: str = "f") -> List[Conjecture]:
        """Generate conjectures about function symmetries."""
        from .patterns import SymmetryDetector
        sym = SymmetryDetector.detect_function_symmetry(f, dim)
        new_conjectures = []

        if sym.get("even"):
            c = Conjecture(f"Function '{name}' is even: {name}(-x) = {name}(x)",
                           ConjectureType.INVARIANCE, source="symmetry_detection")
            c.add_evidence("Verified numerically over 200 random samples")
            new_conjectures.append(c)
        if sym.get("odd"):
            c = Conjecture(f"Function '{name}' is odd: {name}(-x) = -{name}(x)",
                           ConjectureType.INVARIANCE, source="symmetry_detection")
            c.add_evidence("Verified numerically over 200 random samples")
            new_conjectures.append(c)
        if sym.get("periodic"):
            T = sym["estimated_period"]
            c = Conjecture(f"Function '{name}' is periodic with period T ~ {T:.4f}",
                           ConjectureType.INVARIANCE, source="autocorrelation")
            c.add_evidence(f"Autocorrelation peak at lag = {T:.4f}")
            new_conjectures.append(c)

        self.conjectures.extend(new_conjectures)
        return new_conjectures

    def analyze_dynamical_system(self, trajectory: np.ndarray,
                                  name: str = "system") -> List[Conjecture]:
        """Generate conjectures about conserved quantities."""
        from .patterns import InvariantFinder
        conserved = InvariantFinder.find_conservation_laws(trajectory)
        new_conjectures = []

        for c_law in conserved:
            c = Conjecture(
                f"System '{name}' conserves {c_law['name']} "
                f"(value ~ {c_law['mean_value']:.6f}, variation: {c_law['relative_variation']:.2e})",
                ConjectureType.DYNAMICAL, source="conservation_analysis",
            )
            c.add_evidence(f"Relative variation = {c_law['relative_variation']:.2e} over {len(trajectory)} points")
            c.confidence = 0.9 if c_law["relative_variation"] < 1e-6 else 0.6
            c.status = ConjectureStatus.SUPPORTED
            new_conjectures.append(c)

        self.conjectures.extend(new_conjectures)
        return new_conjectures

    def analyze_transformation_invariance(self, f: Callable, transforms: Dict[str, Callable],
                                            data: np.ndarray, name: str = "f") -> List[Conjecture]:
        """Test if f is invariant under various transformations."""
        from .patterns import SymmetryDetector
        new_conjectures = []

        for t_name, transform in transforms.items():
            result = SymmetryDetector.detect_invariant(f, transform, data)
            if result["invariant"]:
                c = Conjecture(
                    f"Function '{name}' is invariant under '{t_name}': "
                    f"{name}(T(x)) = {name}(x)",
                    ConjectureType.INVARIANCE, source="invariance_test",
                )
                c.add_evidence(f"Error = {result['error']:.2e} over {len(data)} samples")
                new_conjectures.append(c)

        self.conjectures.extend(new_conjectures)
        return new_conjectures

    def report(self) -> str:
        lines = [f"=== Conjecture Report ({len(self.conjectures)} hypotheses) ==="]
        for status in ConjectureStatus:
            filtered = [c for c in self.conjectures if c.status == status]
            if filtered:
                lines.append(f"\n  {status.value.upper()} ({len(filtered)}):")
                for c in filtered:
                    lines.append(f"    {c.summary()}")
        return "\n".join(lines)
